language: 'en-GB'
reviews:
    poem: false
    review_status: false
    collapse_walkthrough: true
    high_level_summary: true
    path_filters:
        - '!**/src/**/*'
        - '!dist/'
        - 'lib'
    auto_review:
        enabled: true
        drafts: true
